### ISSUE TITLE
BezierSpine strange behavior

### ISSUE THREAD

**Issue by kimpressive** [fabric-engine/Kraken#349]
Getting this strange behavior where the Spine rotates in X when the control is rotated in Z in the BezierSpine setup. Im having a look at the problem right now but if you know the reason why this  is happening and/or if this is intended, then I would love some help :)

https://gfycat.com/CalmThisBrahmanbull

**Comment by phtaylor** [comment]
hi kimressive, I'll take a look at this today.

**Comment by phtaylor** [comment]
ok, this is fixed now. The fix is on the develop_2.X branch.
The spine was pre-aligned in the wrong direction, which messed up the math after that. 
Let me know if it works as you expected now.

**Comment by EricTRocks** [comment]
I'm still getting drifting when you rotate the top IK control on the Z axis. The spine orientations should stay completely still when manipulating the control unless it's translated or rotated in Y.

**Comment by phtaylor** [comment]
Are you testing on develop_2.X?

**Comment by EricTRocks** [comment]
Phil and I discussed and this is behaving as expected. We need to change the spine component so that the 2nd control from the top is parented under the top control instead of the other way around.
